package models;
// Generated Jun 12, 2017 10:46:59 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Agenda generated by hbm2java
 */
@Entity
@Table(name="agenda"
    ,catalog="conference"
)
public class Agenda  implements java.io.Serializable {


     private Integer id;
     private String hall;
     private Date date;
     private int timeCap;
     private String type;
     private int room;
     private Set<UserAgenda> userAgendas = new HashSet<UserAgenda>(0);
     private Set<Lecture> lectures = new HashSet<Lecture>(0);
     private Set<GalleryPhoto> galleryPhotos = new HashSet<GalleryPhoto>(0);

    public Agenda() {
    }

	
    public Agenda(String hall, Date date, int timeCap, String type, int room) {
        this.hall = hall;
        this.date = date;
        this.timeCap = timeCap;
        this.type = type;
        this.room = room;
    }
    public Agenda(String hall, Date date, int timeCap, String type, int room, Set<UserAgenda> userAgendas, Set<Lecture> lectures, Set<GalleryPhoto> galleryPhotos) {
       this.hall = hall;
       this.date = date;
       this.timeCap = timeCap;
       this.type = type;
       this.room = room;
       this.userAgendas = userAgendas;
       this.lectures = lectures;
       this.galleryPhotos = galleryPhotos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="hall", nullable=false)
    public String getHall() {
        return this.hall;
    }
    
    public void setHall(String hall) {
        this.hall = hall;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="time_cap", nullable=false)
    public int getTimeCap() {
        return this.timeCap;
    }
    
    public void setTimeCap(int timeCap) {
        this.timeCap = timeCap;
    }

    
    @Column(name="type", nullable=false, length=50)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="room", nullable=false)
    public int getRoom() {
        return this.room;
    }
    
    public void setRoom(int room) {
        this.room = room;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="agenda")
    public Set<UserAgenda> getUserAgendas() {
        return this.userAgendas;
    }
    
    public void setUserAgendas(Set<UserAgenda> userAgendas) {
        this.userAgendas = userAgendas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="agenda")
    public Set<Lecture> getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Set<Lecture> lectures) {
        this.lectures = lectures;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="agenda")
    public Set<GalleryPhoto> getGalleryPhotos() {
        return this.galleryPhotos;
    }
    
    public void setGalleryPhotos(Set<GalleryPhoto> galleryPhotos) {
        this.galleryPhotos = galleryPhotos;
    }




}


