package models;
// Generated Jun 8, 2017 6:33:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Author generated by hbm2java
 */
@Entity
@Table(name="author"
    ,catalog="conference"
)
public class Author  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set lectures = new HashSet(0);

    public Author() {
    }

	
    public Author(String name) {
        this.name = name;
    }
    public Author(String name, Set lectures) {
       this.name = name;
       this.lectures = lectures;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="author_lecture", catalog="conference", joinColumns = { 
        @JoinColumn(name="author_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="lecture_id", nullable=false, updatable=false) })
    public Set getLectures() {
        return this.lectures;
    }
    
    public void setLectures(Set lectures) {
        this.lectures = lectures;
    }




}


