package models;
// Generated Jun 12, 2017 10:46:59 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lecture generated by hbm2java
 */
@Entity
@Table(name="lecture"
    ,catalog="conference"
)
public class Lecture  implements java.io.Serializable {


     private Integer id;
     private Agenda agenda;
     private String title;
     private Date beginTime;
     private Date endTime;
     private String status;
     private Set<Author> authors = new HashSet<Author>(0);

    public Lecture() {
    }

	
    public Lecture(Agenda agenda, String title, Date beginTime, Date endTime, String status) {
        this.agenda = agenda;
        this.title = title;
        this.beginTime = beginTime;
        this.endTime = endTime;
        this.status = status;
    }
    public Lecture(Agenda agenda, String title, Date beginTime, Date endTime, String status, Set<Author> authors) {
       this.agenda = agenda;
       this.title = title;
       this.beginTime = beginTime;
       this.endTime = endTime;
       this.status = status;
       this.authors = authors;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="agenda_id", nullable=false)
    public Agenda getAgenda() {
        return this.agenda;
    }
    
    public void setAgenda(Agenda agenda) {
        this.agenda = agenda;
    }

    
    @Column(name="title", nullable=false)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="begin_time", nullable=false, length=8)
    public Date getBeginTime() {
        return this.beginTime;
    }
    
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="end_time", nullable=false, length=8)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    
    @Column(name="status", nullable=false)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="author_lecture", catalog="conference", joinColumns = { 
        @JoinColumn(name="lecture_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="author_id", nullable=false, updatable=false) })
    public Set<Author> getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(Set<Author> authors) {
        this.authors = authors;
    }




}


