package models;
// Generated Jun 8, 2017 6:33:21 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserAgenda generated by hbm2java
 */
@Entity
@Table(name="user_agenda"
    ,catalog="conference"
)
public class UserAgenda  implements java.io.Serializable {


     private Integer id;
     private Agenda agenda;
     private User user;
     private int comment;
     private int rating;

    public UserAgenda() {
    }

    public UserAgenda(Agenda agenda, User user, int comment, int rating) {
       this.agenda = agenda;
       this.user = user;
       this.comment = comment;
       this.rating = rating;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="agenda_id", nullable=false)
    public Agenda getAgenda() {
        return this.agenda;
    }
    
    public void setAgenda(Agenda agenda) {
        this.agenda = agenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="comment", nullable=false)
    public int getComment() {
        return this.comment;
    }
    
    public void setComment(int comment) {
        this.comment = comment;
    }

    
    @Column(name="rating", nullable=false)
    public int getRating() {
        return this.rating;
    }
    
    public void setRating(int rating) {
        this.rating = rating;
    }




}


